apiVersion: batch/v1
kind: Job
metadata:
  name: wait-hook
  labels:
    {{- include "py.labels" . | nindent 4 }}    
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded    
spec:
  backoffLimit: 0
  template:
    metadata:
      name: curl-job
    spec:
      restartPolicy: Never
      containers:
      - name: curl-container
        image: alpine:latest
        command: ["sh", "-c", "for i in {1..2}; do echo 'Just waiting'; sleep 30; done"]
      terminationGracePeriodSeconds: 30
  ttlSecondsAfterFinished: 0

